name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Packages
        run: yarn install
      - name: Run ESLint
        run: yarn lint
